import time
import os
from linebot.v3.messaging import (
    Configuration,
    ApiClient,
    MessagingApi,
    PushMessageRequest,
    TextMessage,
)
from pprint import pprint
from dotenv import load_dotenv

load_dotenv()

configuration = Configuration(access_token=os.environ["LINE_BEARER_TOKEN"])


def send_push_message(job_name: str, message: str) -> None:
    with ApiClient(configuration) as api_client:
        now = time.localtime()
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S", now)
        # Create an instance of the API class
        api_instance = MessagingApi(api_client)
        push_message_request = PushMessageRequest(
            to=os.environ["LINE_USER_UUID"],
            messages=[
                TextMessage(
                    text=f"[研究通知]\n任務: {job_name}\n時間: {timestamp}\n訊息: {message}"
                )
            ],
        )  # PushMessageRequest |
        x_line_retry_key = None  # str | Retry key. Specifies the UUID in hexadecimal format (e.g., `123e4567-e89b-12d3-a456-426614174000`) generated by any method. The retry key isn't generated by LINE. Each developer must generate their own retry key.  (optional)

        try:
            api_response = api_instance.push_message(
                push_message_request, x_line_retry_key=x_line_retry_key
            )
            print("The response of MessagingApi->push_message:\n")
            pprint(api_response)
        except Exception as e:
            print("Exception when calling MessagingApi->push_message: %s\n" % e)
